#!/bin/bash

###############################################################################
# Copyright (c) 2010-2011 Los Alamos National Security, LLC.
#                         All rights reserved.
#
# This program was prepared by Los Alamos National Security, LLC at Los Alamos
# National Laboratory (LANL) under contract No. DE-AC52-06NA25396 with the U.S.
# Department of Energy (DOE). All rights in the program are reserved by the DOE
# and Los Alamos National Security, LLC. Permission is granted to the public to
# copy and use this software without charge, provided that this Notice and any
# statement of authorship are reproduced on all copies. Neither the U.S.
# Government nor LANS makes any warranty, express or implied, or assumes any
# liability or responsibility for the use of this software.
################################################################################

# Author: Samuel K. Gutierrez

# target binary
mmu_target=mpi_mem_usage
# run command
mmu_run_cmd="aprun"
#mmu_run_cmd="mpirun"
# CC
mmu_cc=cc
#mmu_cc=mpicc
# ppn
mmu_ppn=16
# max ppn
mmu_max_procs=32
# multiplier (mmu_ppn * mmu_mult * i) for i = 1,2,3,...,n
mmu_mult=2
# stats base directory
mmu_stats_dir=MMU_STATS
