#!/usr/bin/env python

###############################################################################
# Copyright (c)      2017 Los Alamos National Security, LLC.
#                         All rights reserved.
###############################################################################

import os
import sys
import imp
import subprocess


###############################################################################
class RunConfiguration:
    def __init__(self, config_path):
        self.config_path = config_path
        self.mod_name = self.get_mod_name(config_path)
        self.user_config_mod = self.import_name(self.mod_name, config_path)
        self.user_config = self.user_config_mod.MemnesiaStudyConfig()

    def import_name(self, mod_name, config_path):
        mod = None
        try:
            mod = imp.load_source(mod_name, config_path)
        except ImportError as e:
            print('Cannot import configuration file: {}'.format(e.message))
            return None
        return mod

    def get_mod_name(self, config_path):
        file_name = os.path.basename(config_path)
        if (file_name.endswith('.py')):
            return file_name[:-3]


class Runner:
    def __init__(self, run_config):
        self.run_config = run_config.user_config

    def run(self, test=False):
        print('# Running the following Study')
        self.run_config.emit_config(sys.stdout)

        numpe_runcmd = self.run_config.numpe_runcmd

        for numpe, rcmd in sorted(numpe_runcmd.iteritems()):
            if (test):
                print('run: {}'.format(rcmd))
                continue
            # Else actually run the thing.
            p = subprocess.Popen(
                    rcmd,
                    shell=True,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT
                )
            # Show progress.
            while (True):
                o = p.stdout.readline()
                sys.stdout.write(o)

                if o == '' and p.poll() is not None:
                    break

            retval = p.wait()
            if (retval != 0):
                print('RUN FAILURE: {}'.format(rcmd))


###############################################################################
def usage():
    print('usage: memnesia-run-scaling-study config_file.py')


###############################################################################
def check_args(argv):
    if len(argv) != 2:
        usage()
        exit(os.EX_USAGE)

    configf = argv[1]

    if not os.path.isfile(configf) or not configf.endswith('.py'):
        print("'{}' is not a config file. Cannot continue.".format(configf))
        usage()
        exit(os.EX_USAGE)


###############################################################################
def main(argv=None):
    if argv is None:
        argv = sys.argv

    check_args(argv)

    runner = Runner(RunConfiguration(argv[1]))
    runner.run()

    return os.EX_OK


###############################################################################
###############################################################################
###############################################################################
if __name__ == "__main__":
    sys.exit(main())
